// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkBtJriZJg_NTZlK3JYQXdvQpu08V7Ra8',
    appId: '1:846522861070:web:afe9f753f37107521e5e5f',
    messagingSenderId: '846522861070',
    projectId: 'blogapp-23da1',
    authDomain: 'blogapp-23da1.firebaseapp.com',
    storageBucket: 'blogapp-23da1.appspot.com',
    measurementId: 'G-1J4TE31BZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBULWmc8Ug7rmV6aPZXwki5-nriWVENDHE',
    appId: '1:846522861070:android:4e70ad6e42cf0fa81e5e5f',
    messagingSenderId: '846522861070',
    projectId: 'blogapp-23da1',
    storageBucket: 'blogapp-23da1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYlsM8UxdEibK8x_xBkwm8A5kpcHuaOfc',
    appId: '1:846522861070:ios:7e3dd60163371d591e5e5f',
    messagingSenderId: '846522861070',
    projectId: 'blogapp-23da1',
    storageBucket: 'blogapp-23da1.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYlsM8UxdEibK8x_xBkwm8A5kpcHuaOfc',
    appId: '1:846522861070:ios:1fb6e2bca580d8ae1e5e5f',
    messagingSenderId: '846522861070',
    projectId: 'blogapp-23da1',
    storageBucket: 'blogapp-23da1.appspot.com',
    iosBundleId: 'com.example.blogApp.RunnerTests',
  );
}
