name: blog_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  json_annotation: ^4.8.1
  mocktail: ^0.3.0
  auto_route: ^7.7.0
  path_provider: ^2.0.14
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  google_sign_in: ^6.1.0
  formz: ^0.6.0
  logger: ^1.3.0
  font_awesome_flutter: ^10.4.0
  uuid: ^4.0.0
  firebase_storage: ^11.2.2
  intl: ^0.18.0
  scrollable_positioned_list: ^0.3.8
  flex_color_scheme: ^7.1.2
  autocomplete_textfield: ^2.0.1
  dropdown_button2: ^2.1.4
  fluttertoast: ^8.2.2
  shimmer: ^3.0.0
  email_validator: ^2.1.17
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.2.0
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true

  assets:
     - assets/


